### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nimtomd#1]
- [ ] Cleanup
- [ ] [1] - not* includes comments from Ordinal*
- [ ] [1] - *{ is not recognized
- [ ] [2] - 1-line global with comment below is not recognized
- [ ] If there's a new line after an inline ..code-block::, it will append a blank line
- [ ] Update README with info about required style. Maybe check with nimpretty and tell the user?
 
system.nim:
**[1]**
```nim
proc `not`*(a: typedesc): typedesc {.magic: "TypeTrait", noSideEffect.}
  ## Constructs an `not` meta class

type
  Ordinal* {.magic: Ordinal.}[T] ## Generic ordinal type. Includes integer,
                                 ## bool, character, and enumeration types
                                 ## as well as their subtypes. Note `uint`
                                 ## and `uint64` are not ordinal types for
                                 ## implementation reasons
  `ptr`* {.magic: Pointer.}[T] ## built-in generic untraced pointer type
  `ref`* {.magic: Pointer.}[T] ## built-in generic traced pointer type
```
**[2]**
```nim
  SomeSignedInt* = int|int8|int16|int32|int64
    ## type class matching all signed integer types

  SomeUnsignedInt* = uint|uint8|uint16|uint32|uint64
    ## type class matching all unsigned integer types
```
